### ISSUE TITLE
Protocol Comparison

### ISSUE THREAD

**Issue by nopara73** [zkSNACKs/WabiSabi#11]
| | [Blind Pedersen Commitments](https://github.com/zkSNACKs/WabiSabi/issues/10) | [Blind BLS Signatures](https://github.com/zkSNACKs/WabiSabi/issues/5) |
| ------------- |:-------------:| -----:|
| Crypto      | relatively simple | complex |
| Communication Rounds (Synchronous + Parallel)      | 3+1      |   3+2 |
| Coin Dividing | no privacy loss | no privacy loss |
| Coin Merging | some privacy loss | no privacy loss |
| Protocol Cleanness | introducing denominations are somewhat dirty, Blind-Pedersen Commitments rely on Knowledge assumptions which is pretty new and considered to be non-standard | solving malleability of BLS with accumulators is somewhat dirty |

**Comment by nopara73** [comment]
For the record the communication rounds are such:

Synchronous means participants must wait for each other to get to the next phase.

- Input Registration
- Output Registration
- Transaction Signing

Parallel means participants do not have to wait each other to get to the next phase.

- Asking for unsigned transaction in the beginning of Transaction Signing.

In the case of BLS, the second parallel communication round is asking for the accummulator in the beginning of Output Registration.

**Comment by seresistvanandras** [comment]
I argue, that if the [proposed coin merging method](https://github.com/zkSNACKs/WabiSabi/issues/10#issuecomment-615221246) for the Blind Sig on Pedersen Commitments scheme is correct, then I would change the _**some privacy loss**_ in the table to minimal or **_negligible privacy loss_**. As coordinator would only be able to tell the number of merged UTXOs which is I think in most of the cases also deductable given the blockchain data. This is especially true for payment values. 

Pls review and try to break the [proposed coin merging protocol](https://github.com/zkSNACKs/WabiSabi/issues/10#issuecomment-615221246).

**Comment by nothingmuch** [comment]
i think we can now update this considering #5, #10 and #16 

1. crypto complexity should be made more concrete, depending on whether the following are required:
    - bilinear groups
    - accumulators
    - zk proofs other than sigma protocols
2. approach to double spending protection
    - unique signatures
    - traceability (a la offline e-cash schemes)
3. engineering/implementation considerations
    - in the context of C#
    - in the context of wider bitcoin ecosystem
4. marketability to bitcoin crowd
    - how simple to understand the blindness/unlinkability is
    - how conservative primitives are relative to those already in bitcoin

**Comment by nopara73** [comment]
https://github.com/zkSNACKs/WabiSabi/issues/30
