### ISSUE TITLE
Protocol: KVAC based

### ISSUE THREAD

**Issue by nothingmuch** [zkSNACKs/WabiSabi#17]
I had a brain fart and for some reason I put down algebraic MACs in #13 as relying on bilinear groups, and consequentially we did not look at them in much detail. This is **not** the case. Again I have @jonasnick to thank for prompting me to look again at [Keyed-Verification Anonymous Credentials (KVACs)](https://smeiklej.com/files/ccs14.pdf).

The gist of KVAC is that it is designed for when the issuer is also the verifier, like in our use case.

A newer scheme: [The Signal Private Group System and Anonymous
Credentials Supporting Efficient Verifiable Encryption](https://signal.org/blog/pdfs/signal_private_group_system.pdf) allows attributes to be group elements: for our use case the attributes can be Pederesen Commitments to amounts.

Since this scheme allows unlinkable multi-show, this reintroduces the double spending problem. However, this should be easily solvable by introducing serial numbers which are revealed as part of credential showing.

Note that by only using Pedersen commitments as group attributes we don't require the blind issuance protocol of either KVAC scheme, which relies on ElGamal encryption of the requested attributes, which has the nice benefit of perfect hiding of the sub-amounts and serial numbers, so the coordinator can't retrospectively de-anonymize users even if there is a crypto break.

## Input Registration

The user submits a request for N credentials, with either 1 or 2 group attributes (not clear which is simpler yet):

- Two separate Pedersen commitments, one for the sub-amount and one for the serial number.
- A single Pedersen multi commitment for a requested sub-amount and serial number.

Along with a range proof for each amount commitment, and a proof that the sum of all the amount commitments matches the input amount.

The coordinator verifies the proofs, and responds with N MACs on the requested attributes, along with a proof of knowledge of the secret key.

## Output Registration

The user executes the `Show` protocol for the combination of credentials they want to use, which produces as output randomized commitments to the attributes and a proof of the MAC verification.

The user also proves that the serial number commitments can be opened to their corresponding serial numbers. These serial numbers are revealed for double spending protection, but the commitment opening should be done in zero knowledge to avoid revealing the randomness of the original commitment in the input registration phase or the randomization added in the `Show` protocol.

The user also proves that the sum of the amount attributes matches the output amount, analogously to input registration (but there is no need for range proofs at this phase).

The user submits these proofs, the randomized attributes, and the serial numbers.

Note that the serial numbers should not be "revealed attributes" as I previously stated, since those would be trivially linkable to input registration.

Note that since all proofs are created with sigma protocol, the 2n+1 proofs should be composable into a proof of their conjunction. I believe this also holds if using bulletproofs for the range proofs at input registration.

## Self Issuance

The (sub-)proof of MAC validity could be modified so that a credential is considered valid if it has a valid MAC **OR** the amount it certifies is exactly 0.

Since users could then generate such credentials without ever contacting the server, this makes it possible to *require* valid credentials to be shown at input registration, which would allow users merge an arbitrary number of inputs together into a single credential without requiring the output registration phase to accept as many credentials as there are inputs.

As few as 1 spent & newly requested credentials per input/output registration operation are needed if output registrations also produce newly signed credentials for the remaining amount, but ideally a larger number on the order of log(participants) should be used to allow users to make parallel requests for improved privacy.

**Comment by nothingmuch** [comment]
Since attributes cannot be shown separately for a single credential covering multiple amounts the serial numbers would have to be hidden attributes as far as the credential showing, but then proven equal to some public input.

Anyway, the more I think about it the more needlessly complex the approach of having multiple attributes under a single credential approach seems, but i still think having one credential per amount is strictly an improvement over #16

**Comment by nopara73** [comment]
> The main advantage over #16 would be smaller tokens and reduced interactions during issuance, as well, and it also seems like this requires fewer group operations.

- smaller tokens -> we don't really care.
- reduced interactions during issuance -> we care, but how can the interactions be reduced while ACL already has the theoretically minimal interactions in the first place?
- this requires fewer group operations -> what does this mean? does this mean it reduces computational load, in which case we don't really care, or it means it makes the overall scheme simpler, in which case we care?

**Comment by nopara73** [comment]
>  A better approach might be to request a single KVAC for multiple sub-amounts, and relying on the unlinkable multi-show property of the algebraic MAC scheme to keep these unlinkable.

I'm not sold. This seem to make the scheme more complex and the gain is less things gets communicated over the network, which we don't care as it does not seem to be a significant gain. Is this a fair assessment?

**Comment by nopara73** [comment]
> If we can achieve this would be a significant efficiency improvement for input registration over #16 because a single credential can cover many amounts.

I disagree. There's no efficiency gain in the big picture. Empirically I suspect we're fine to transmit data that's <= 100KB without much penalty. FTR I'm going on a bit of tangent: theoretically 512 bytes is a Tor cell size so making data smaller than that makes no difference as Tor would just fill the remaining things up with fake data. In fact, a compression is usually applied before transmitting data, where we can assume something like 1KB of raw data after compressed would get into only a single cell.

**Comment by nothingmuch** [comment]
> > A better approach might be to request a single KVAC for multiple sub-amounts, and relying on the unlinkable multi-show property of the algebraic MAC scheme to keep these unlinkable.
> 
> I'm not sold. This seem to make the scheme more complex and the gain is less things gets communicated over the network, which we don't care as it does not seem to be a significant gain. Is this a fair assessment?

yes, i think that approach has many downsides and additional complexity, and we should remove it from consideration leaving only the "naive" approach

**Comment by nothingmuch** [comment]
>     * reduced interactions during issuance -> we care, but how can the interactions be reduced while ACL already has the theoretically minimal interactions in the first place?

actually it doesn't, some of the proofs required for the 3 stages are interactive
 
>     * this requires fewer group operations -> what does this mean? does this mean it reduces computational load, in which case we don't really care, or it means it makes the overall scheme simpler, in which case we care?

both senses, but we should mainly care about the simplicity of the protocol, especially in explaining how unlinkability is achieved (i think ACL's main downside is that this aspect is rather complex)

**Comment by seresistvanandras** [comment]
> > * reduced interactions during issuance -> we care, but how can the interactions be reduced while ACL already has the theoretically minimal interactions in the first place?
> 
> actually it doesn't, some of the proofs required for the 3 stages are interactive
> 
Which proofs are interactive in the ACL-based scheme? I think all of them can be made non-interactive via the Fiat-Shamir heuristic! What am I missing?

**Comment by nothingmuch** [comment]
> Which proofs are interactive in the ACL-based scheme? I think all of them can be made non-interactive via the Fiat-Shamir heuristic! What am I missing?

hmm, you're right about the first one:

Since the Fiat Shamir heuristic is already used in the signature scheme, I thought there was some reason why the proof in the registration phase must be interactive, but reviewing it now I can't find one:

> During registration the User and the Signer carry out a standard interactive zero-knowledge proof of knowledge protocol where the User creates a proof π1 to convince the Signer that he knows an opening of the commitment C.

but the sigma protocol for producing the OR proof is still interactive, so even if combining the Preparation and Validation obtaining the signature requires 2 round trips (coordinator first gives `rnd`, user responds with `e`, and finally gets `c, r, c', r'`).

I don't think this is a serious issue since this is per client

**Comment by nothingmuch** [comment]
Note that there is [a third KVAC scheme](https://eprint.iacr.org/2019/117.pdf) I was not aware of, which natively supports pseudonymous showing, which removes the requirement for a serial number, but it also supports anonymity revocation using a trusted party, which is undesirable for this use case even if the trusted party's keys are set up with hash-to-curve.

This scheme also supports non interactive ZK proofs without the Fiat-Shamir heuristic, but I don't think this changes anything for our use case since Bitcoin already relies on that in its digital signature scheme, and lacks security proofs for other aspects of its security even in the random oracle model.

**Comment by nothingmuch** [comment]
i updated the top post to remove the more complicated approach, which has no real advantages (even the ones i speculated about seem invalid).

**Comment by nopara73** [comment]
> The coordinator verifies the proofs, and responds with N MACs on the requested attributes, along with a proof of knowledge of the secret key.

Why does the coordinator have to prove he knows the secret key?  
Assuming it does need to, then does this mean the coordinator signs some random string the user chooses or there needs to be a more complex zero knowledge protocol to be executed here?

**Comment by nothingmuch** [comment]
> Why does the coordinator have to prove he knows the secret key?

Since the user can't verify the MAC without the secret key, this assures for the user that the parameters are the same for everyone, so that the coordinator can't tag users by using a different key. There may be another reason. It's not required if only using the MAC algorithms as MACs and using VerifyMAC directly, but it is for the key verifiable anonymous credential security.

> Assuming it does need to, then does this mean the coordinator signs some random string the user chooses or there needs to be a more complex zero knowledge protocol to be executed here?

Those are kind of the same thing, e.g. a Schnorr digital signature is a zero knowledge proof of knowledge of the discrete log of the a group element with respect to some generator, and it's made non-interactive using the Fiat Shamir heuristic, instead of the verifier choosing a challenge randomly, the prover gets one out of a hash function.

**Comment by seresistvanandras** [comment]
A bit more formal presentation of the proposed coin splitting and merging is presented below in the context of the KVAC-scheme.

Each registered UTXO has two attributes: a value and a serial number. They are both committed in Pedersen commitments, i.e. ![$M_v=\mathit{Com}(v,r_v),M_s=\mathit{Com}(s,r_s)$](https://render.githubusercontent.com/render/math?math=%24M_v%3D%5Cmathit%7BCom%7D(v%2Cr_v)%2CM_s%3D%5Cmathit%7BCom%7D(s%2Cr_s)%24).

1. Input UTXO splitting
Since input UTXO values are still committed in Pedersen commitments, hence input UTXO splitting works just like in all the previous schemes.

2. UTXO merging
Suppose user wants to merge two UTXOs at output registration with secret values ![$v,v'$](https://render.githubusercontent.com/render/math?math=%24v%2Cv'%24) to a UTXO with public value ![$v_{\mathit{out}}$](https://render.githubusercontent.com/render/math?math=%24v_%7B%5Cmathit%7Bout%7D%7D%24). User needs to convince the coordinator that ![$v_{\mathit{out}}=v+v'$](https://render.githubusercontent.com/render/math?math=%24v_%7B%5Cmathit%7Bout%7D%7D%3Dv%2Bv'%24). 

User has two Pedersen multi-commitments to the input UTXO values she would like to merge: ![$C_{y_{v}},C^{'}_{y_{v}}$](https://render.githubusercontent.com/render/math?math=%24C_%7By_%7Bv%7D%7D%2CC%5E%7B'%7D_%7By_%7Bv%7D%7D%24). Each commitment has the following structure:  ![$C_{y_{v}}=G^{z}_{y_v}M_v=G^{z}_{y_{v}}h^{v}g^{r}$](https://render.githubusercontent.com/render/math?math=%24C_%7By_%7Bv%7D%7D%3DG%5E%7Bz%7D_%7By_v%7DM_v%3DG%5E%7Bz%7D_%7By_%7Bv%7D%7Dh%5E%7Bv%7Dg%5E%7Br%7D%24). Therefore multiplying the two commitments we'll have ![$C_{y_{v}}\cdot C^{'}_{y_{v}}=G^{z}_{y_v}M_{v}\cdot G^{z'}_{y_v}M_{v^'}=G^{z+z'}_{y_{v}}h^{v+v'}g^{r+r'}$](https://render.githubusercontent.com/render/math?math=%24C_%7By_%7Bv%7D%7D%5Ccdot%20C%5E%7B'%7D_%7By_%7Bv%7D%7D%3DG%5E%7Bz%7D_%7By_v%7DM_%7Bv%7D%5Ccdot%20G%5E%7Bz'%7D_%7By_v%7DM_%7Bv%5E'%7D%3DG%5E%7Bz%2Bz'%7D_%7By_%7Bv%7D%7Dh%5E%7Bv%2Bv'%7Dg%5E%7Br%2Br'%7D%24). The proof contains of ![$\pi=(z+z',r+r')$](https://render.githubusercontent.com/render/math?math=%24%5Cpi%3D(z%2Bz'%2Cr%2Br')%24), i.e. coordinator learns ![$h^{v+v'}$](https://render.githubusercontent.com/render/math?math=%24h%5E%7Bv%2Bv'%7D%24)  and checks whether ![$h^{v+v'}=h^{v_{\mathit{out}}}$](https://render.githubusercontent.com/render/math?math=%24h%5E%7Bv%2Bv'%7D%3Dh%5E%7Bv_%7B%5Cmathit%7Bout%7D%7D%7D%24). 

- Soundness is achieved as user does not know the discrete logarithms between generator points used in the commitment scheme. 

- Zero-knowledge is ensured as the revealed sums do not leak anything about individual ![$r,r',z,z'\mod q$](https://render.githubusercontent.com/render/math?math=%24r%2Cr'%2Cz%2Cz'%5Cmod%20q%24).

**Comment by nothingmuch** [comment]
Hmm, this is exactly equivalent to what we discussed in the call, where we end up with a commitment to 0 and open that as ![$(z+z'-z'',r+r'-r'')$](https://render.githubusercontent.com/render/math?math=%24(z%2Bz'-z''%2Cr%2Br'-r'')%24), right?

Is it worth rewriting these for n credentials instead of 2? there's no loss of generality in assuming n=2, as we did on the board, but I think it would be clearer, and we did free up numerical subscripts by indexing the different attributes as `v` and `s`.

Secondly, for each credential `M_s` commitment is, the user submits ![$(s, \frac{C_{y_s}}{h^s}) = (s, G_{y_s}^z g^{r_s})$](https://render.githubusercontent.com/render/math?math=%24(s%2C%20%5Cfrac%7BC_%7By_s%7D%7D%7Bh%5Es%7D)%20%3D%20(s%2C%20G_%7By_s%7D%5Ez%20g%5E%7Br_s%7D)%24), which the coordinator can then verify without linking to a specific ![M_s](https://render.githubusercontent.com/render/math?math=M_s).

Note that after the coordinator has learned `s`, the original ![M_s](https://render.githubusercontent.com/render/math?math=M_s) commitments are no longer prefectly hiding, since there is exactly one ![r_s \in \mathbb{Z}_q](https://render.githubusercontent.com/render/math?math=r_s%20%5Cin%20%5Cmathbb%7BZ%7D_q) where ![h^s g^{r_s} = M_s](https://render.githubusercontent.com/render/math?math=h%5Es%20g%5E%7Br_s%7D%20%3D%20M_s).

This is admittedly a contrivance, but I think it's still desirable to preserve unconditional hiding, so that we can be sure that the coordinator can't ever de-anonymize users retrospectively even in case of a crypto break. If I'm not mistaken, I think all we would need is to add another randomness term to the serial number commitment with a 3rd generator, so that ![$M_s = g^s h_1^{r_{s1}} h_2^{r_{s2}}$](https://render.githubusercontent.com/render/math?math=%24M_s%20%3D%20g%5Es%20h_1%5E%7Br_%7Bs1%7D%7D%20h_2%5E%7Br_%7Bs2%7D%7D%24).

**Comment by nopara73** [comment]
https://github.com/zkSNACKs/WabiSabi/issues/30
