### ISSUE TITLE
Alternative Approaches

### ISSUE THREAD

**Issue by nopara73** [zkSNACKs/WabiSabi#3]
It could be useful to list our considered alternative approaches in the final paper. Here I collect them in this issue.

- CashFusion
- Building something with Divisible E-Cash
- RingCT
- whatever zcash is doing

**Comment by seresistvanandras** [comment]
Maybe I will make separate issues for all the possible blind signature schemes to discuss their pros and cons in separate github issues...I'm quite confident we could achieve what we want with some cool blind signature scheme. Maybe we also need to apply some accumulators or range proof systems, but for me the main question seems to be the choice of the proper blind signature scheme. Although, I agree, that it is valuable to consider alternative approaches. :)

**Comment by nopara73** [comment]
https://github.com/zkSNACKs/WabiSabi/issues/30
