### ISSUE TITLE
meta: issue cleanup

### ISSUE THREAD

**Issue by nothingmuch** [zkSNACKs/WabiSabi#30]
it seems to me that many of the issues are no longer relevant and can be closed:

- design space #3, #13, #11 
- building blocks that are no longer relevant: #4, #12, #14
- proposed protocols superseded by #17, which itself has been superseded by the draft doc: #5, #10, #16

**Comment by nopara73** [comment]
I agree with all. I'll close them (and this.) If someone doesn't agree feel free to reopen it.
