### ISSUE TITLE
Eliminate serial number attribute

### ISSUE THREAD

**Issue by nothingmuch** [zkSNACKs/WabiSabi#42]
@RubenSomsen suggested a way to prevent double spending without needing a serial number attribute.

First, observe that instead of revealing the serial number `s`, with a new generator `G_r` knowledge of `s` can be proven revealing only a curve point `C_r = G_r^s`. This commitment does not contain `z`, so it's fixed for a single attribute and can be used as a serial number/nullifier if the proof also relates the witness `s` to `C_s`.

Next, to eliminate the serial number attribute we can use the `r` term from the amount commitment (`M_v = G_h^v G_g^r`) instead of `s`, to create `C_r = G_r^r`.

A proof of knowledge of `r` with a statement `(C_r, C_v / G_v^z G_h^v) = (G_r^r, G_g^r)` (DLEQ) is sufficient.

A `G_r` is required because if `G_g` is used the coordinator could brute force the small message space of values to deanonymize the scheme as described in #40.

Like serial numbers this does not provide unconditional hiding but that can be addressed if `M_v` includes additional randomness term with yet another distinct generator.

**Comment by MaxHillebrand** [comment]
That's a neat trick!
But, is it useful? It seems that there is more computational cost [although little] to prove knowledge of the serial number, rather than just showing it.

Can you please explain the benefits of this approach?

**Comment by nothingmuch** [comment]
it saves `k` group elements per registration, makes the iparams smaller (eliminating `y_s`), eliminates one group element per credential showing (C_s) and has roughly the same overhead for the proof of representation we already have where `s` is a public input.

**Comment by jonasnick** [comment]
So you use the randomness of the value commitment as serial number, but you don't reaveal it directly, you show `G_r^r` with some zkp and the server stores `G_r^r`. That's nice and looks like it would work.

**Comment by nopara73** [comment]
@nothingmuch were you referring on Slack to this idea that it doesn't work?

**Comment by MaxHillebrand** [comment]
Yes @nopara73, afaik.

**Comment by nopara73** [comment]
Then it can be closed with an explanation.

**Comment by RubenSomsen** [comment]
@nothingmuch was referring to a different idea that I broke on Slack. It was not related to this.
