### ISSUE TITLE
Protocol docs - Input Registration

### ISSUE THREAD

**Issue by molnard** [zkSNACKs/WabiSabi#91]
At this part https://github.com/zkSNACKs/WabiSabi/blob/master/protocol.md#round-structure

> Alices prove ownership of inputs to the coordinator,
>    which issues credentials **with zero value** for use in mandatory credential
>    presentations.

This seems to be wrong or confusing.

**Comment by nothingmuch** [comment]
it's correct, every request requires credentials to be presented as well as requested, and if either is optional than this can leak information to the server about which credentials were or weren't used to make that request, so these zero value credentials are required for the initial requests
